### ISSUE TITLE
Wrong line-height in Calender app

### ISSUE THREAD

**Issue by adanielvv** [owncloud/apps#1972]
When you click on a late hour in the _day_ or _week_ view the event is created with a half an hour time shift.
### Steps to reproduce
1. Open Firefox
2. [Go to the ownCloud calendar demo](http://demo.owncloud.org/index.php/apps/calendar)
3. Click on the _Day_ or _Week_ button.
4. Click or drag on a late hour
5. _The event is being created with a half an hour time shift_

Applies to:
Calender, Day and Week view
Firefox (also IE8)
Doesn't apply to:
Chromium

My suggestion:
In the file _owncloud/apps/calendar/css/style.css_:

``` css
.fc-agenda .fc-agenda-axis{
        padding:0;
        padding-right:4px;
        line-height:initial; /* my suggestion for a fix for Firefox etc */
}
```
### Client configuration

**Browser:** Firefox
